# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0054_auto_20190411_0749'),
        ('sml', '0002_add_device_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMLVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obis_code', models.CharField(default='', help_text='Obis Kennziffer: `1-0.1.8.0*255`', max_length=400)),
                ('sensor_type', models.CharField(choices=[('ISKAR MT175', 'ISKAR MT175'), ('EYS Q3MA', 'EYS Q3MA')], default='', max_length=10)),
                ('sml_variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='smldevice',
            name='device_id',
            field=models.CharField(blank=True, help_text='e.g. `1 ISK00 XXXXXXXX`', max_length=400),
        ),
        migrations.AddField(
            model_name='smldevice',
            name='pin',
            field=models.IntegerField(blank=True, help_text='to get advanced data from device', null=True),
        ),
    ]
