# Generated by Django 2.2.9 on 2020-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sml', '0003_auto_20200124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smldevice',
            name='pin',
            field=models.IntegerField(blank=True, help_text='to get advanced data from device', null=True),
        ),
    ]
